name: dispach
on:
  workflow_dispatch:
   inputs:
      ambiente:     
        description: 'Configuracion de ambiente'
        required: true
        default: 'qa4'
        type: choice
        options:
        - qa1
        - qa2
        - qa3
        - qa4
        - dev
      servidor:
        description: 'Configuracion de ambiente'
        required: true
        default: 'qa4'
        type: choice
        options:
        - ser01
        - ser02

        
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prueba
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: ${{ inputs.ambiente }}  ${{ inputs.servidor }}
      - name: Run a one
        run: ${{ inputs.servidor }}
        
      #- name: Google Chat Notification
       # uses: paulinthought/google-chat-release-notifier@v2.2
        #with:
         # name: Builds
          #url: https://chat.googleapis.com/v1/spaces/AAAAcezM7MI/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=9SY2ZUxUoGkqrQi1prQ44LTYn0mFJ9vO2HUdwCMjTdo
          #status: ${{ job.status }}
          #info: ": Branch: ${{ github.ref_name }}"
      
