name: Octo Organization CI

on:
  push:
    branches: [main]

jobs:
   example_matrix:
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest] 
    runs-on:  [ubuntu-latest]

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo ${{ matrix.version }}
          
