name: Octo Organization CI
 
on:
  push:
    branches: [main]

jobs:
   example_matrix:
    strategy:
      matrix:
        version: [10, 12, 14]
    
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo ${{ matrix.version }}
          
