name: Octo Organization CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello from Organization runner!
      - name: Google Chat Notification
        uses: Co-qn/google-chat-notification@releases/v1
        with:
          name: Build
          url: https://chat.google.com/room/AAAAcezM7MI?cls=4
          status: ${{ job.status }}
        if: always()
