name: Octo Organization CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, windows , x64]
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello from Organization runner!
