name: Octo Organization CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello from Organization runner
        
      - name: Google Chat Notification
        uses: paulinthought/google-chat-release-notifier@v2.2
        with:
          name: Builds
          url: https://chat.googleapis.com/v1/spaces/AAAAcezM7MI/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=9SY2ZUxUoGkqrQi1prQ44LTYn0mFJ9vO2HUdwCMjTdo
          status: ${{ job.status }}
          info: ": Branch: ${{ github.ref_name }}\nLoglevel: ${{inputs.logLevel}}"
      - name: Google Chat Notification
        uses: paulinthought/google-chat-release-notifier@v2.2
        with:
          name: Build
          url: https://chat.googleapis.com/v1/spaces/AAAAcezM7MI/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=9SY2ZUxUoGkqrQi1prQ44LTYn0mFJ9vO2HUdwCMjTdo
          status: ${{ job.status }}
          info: ": Branch: ${{ github.ref_name }}\nLoglevel: ${{inputs.logLevel}}"
        if: ${{ failure() }}
