name: Octo Organization CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prueba
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello from Organization runner

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: variable Rama
        run: echo ${{ steps.extract_branch.outputs.branch }}
        
      - name: Try to fail
        if:  ${{ steps.extract_branch.outputs.branch != 'main' }}
        run: exit 1
      - name: Print message if we don't fail
        run: echo Should not get here
        
      - name: Google Chat Notification
        uses: paulinthought/google-chat-release-notifier@v2.2
        with:
          name: Builds
          url: https://chat.googleapis.com/v1/spaces/AAAAcezM7MI/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=9SY2ZUxUoGkqrQi1prQ44LTYn0mFJ9vO2HUdwCMjTdo
          status: ${{ job.status }}
          info: ": Branch: ${{ github.ref_name }}"
      - name: Google Chat Notification
        uses: paulinthought/google-chat-release-notifier@v2.2
        with:
          name: Build
          url: https://chat.googleapis.com/v1/spaces/AAAAcezM7MI/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=9SY2ZUxUoGkqrQi1prQ44LTYn0mFJ9vO2HUdwCMjTdo
          status: ${{ job.status }}
          info: ": Branch: ${{ github.ref_name }}"
        if: ${{ failure() }}
